name: lightning_talk_gong
description: Lightning Talk Gong
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  desktop_notifications: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  fonts:
  - family: MaterialIcons
    fonts:
    - asset: assets/MaterialIcons-Regular.ttf
  uses-material-design: true
