name: lightning-talk-gong
version: "0.1"
summary: Lightning Talk Gong
description: |
  When the gong goes bong, stop talking!
grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64

apps:
  lightning-talk-gong:
    command: bin/lightning_talk_gong
    extensions: [gnome-3-28]
    plugs:
      - opengl
      - audio-playback
    environment:
      LD_LIBRARY_PATH: $SNAP/bin/lib:$LD_LIBRARY_PATH
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/usr/share/glvnd/egl_vendor.d/

parts:
  lightning-talk-gong:
    source: .
    plugin: nil
    override-build: |
      set -eux
      flutter channel master
      flutter upgrade
      flutter config --enable-linux-desktop
      flutter doctor
      flutter pub get
      flutter build linux --release -v
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/lib
      cp -r build/linux/release/bundle/* $SNAPCRAFT_PART_INSTALL/bin/
      cp $SNAPCRAFT_PART_INSTALL/../src/gong.wav $SNAPCRAFT_PART_INSTALL/
      find /root/snap/flutter/common/flutter/.pub-cache/ -name libunixdomainsocket.so -exec cp {} $SNAPCRAFT_PART_INSTALL/bin/lib/ \;
    build-snaps:
      - flutter/latest/edge

  libraries:
    plugin: nil
    stage-packages:
      - pulseaudio-utils
      - libegl-mesa0
