name: lightning-talk-gong
version: "0.1"
summary: Lightning Talk Gong
description: |
  When the gong goes bong, stop talking!
grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64

apps:
  lightning-talk-gong:
    command: bin/lightning_talk_gong
    extensions: [flutter-master]
    plugs:
      - opengl
      - audio-playback

parts:
  lightning-talk-gong:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    override-build: |
      set -eux
      snapcraftctl build
      cp $SNAPCRAFT_PART_INSTALL/../src/gong.wav $SNAPCRAFT_PART_INSTALL/
    build-snaps:
      - flutter/latest/edge

  libraries:
    plugin: nil
    stage-packages:
      - pulseaudio-utils
      - libegl-mesa0
